[package]
name = "intro_to_rust_zk"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254 = "0.5.0"
# for perdesen commitments
ark-ec = {version = "0.5.0"}
ark-ff = "0.5.0"
rand = "0.9.2"

[dev-dependencies]
